### ISSUE TITLE
Does SugarRecordFinder support fetchOffset?

### ISSUE THREAD

**Issue by iblacksun** [gitdoapp/SugarRecord#109]
I'm using SugarRecord but have an issue: i can't execute page request.
> fetchRequest.fetchOffset = page * size;
> fetchRequest.fetchLimit = size;

I know SugarRecordFinder have an firsts() function, but can't set offset.
And, SugarRecord.operations give me a SugarRecordContext, so i can't use NSManagedObjectContext direct.

**Comment by pepibumur** [comment]
@iblacksun  it doesn't support fetch offset. I can add support for it but in the meantime you can get the real context from the SugarRecordContext https://github.com/SugarRecord/SugarRecord/blob/develop/library/CoreData/Base/SugarRecordCDContext.swift#L15 .

**Comment by iblacksun** [comment]
@pepibumur Got it, thanks.
