### ISSUE TITLE
Crash when using NSFetchedResultsController

### ISSUE THREAD

**Issue by iblacksun** [gitdoapp/SugarRecord#120]
I'm using NSFetchedResultsController with SugarRecord.operation in background.  
But when context.endWriting(), the App crashed.

<pre>
The exception is
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'cannot find data for a temporary oid: 0x7f992b11e3b0 <x-coredata://7B89F4FA-5B75-46B6-A24C-9D71742358BA/StatusComment/t12BEA25F-A62A-4C99-A6BE-5CD38723312D2>
</pre>
I think is the same issue with #118

**Comment by dchavezlive** [comment]
Could you provide an example or give more details about what you're trying to do?
