### ISSUE TITLE
Compile error in DefaultRealmStack.swift after switch to cocoapods

### ISSUE THREAD

**Issue by ransomweaver** [gitdoapp/SugarRecord#121]
I've changed my project to use cocoapod SugarRecord, removed SugarRecord files from my project and removed Realm.framework from my project, then pod install to get Realm 0.90.5 and SugarRecord 1.0.7 in Pods, and now I get this error:

Missing argument for parameter 'forRealmPath'

in 

DefaultRealmStack.swift::migrateIfNeeded at 

RLMRealm.setSchemaVersion(UInt(lastSchema), withMigrationBlock: { (realmMigration: RLMMigration!, oldSchema: UInt) -> Void in

Realm is of the wrong version for this code perhaps? What to do?

**Comment by jcalavia** [comment]
I have the same issue but in my case I am evaluating SugarRecord using Cocoapods

How is it possible that stable version is not compiling?

Hope you can fix it soon

**Comment by pepibumur** [comment]
Sorry for the defect, I'll try to have it for this friday. @jcalavia  and @ransomweaver

**Comment by jcalavia** [comment]
Hi @pepibumur , what about this?

**Comment by ransomweaver** [comment]
Since the current REALM in HEAD of this project is 0.89.1 it looks like the signature of RLMRealm.setSchemaVersion has changed for 0.90.5 and later and we need to use this now:

RLMRealm.setSchemaVersion(UInt(lastSchema), forRealmAtPath: RLMRealm.defaultRealmPath() , withMigrationBlock:

in migrateIfNeeded()

Does that cause any problems to use defaultRealmPath()? The file is called DefaultRealmStack.swift... but what about migrations that use a Realm at a custom Path?

I don't really want to fork SugarRecord over this issue, since it only affects migration, and wait for @pepibumur  to to move to a more recent Realm in HEAD.

**Comment by XBeg9** [comment]
Any news on this?

**Comment by lamoni** [comment]
+1

**Comment by pepibumur** [comment]
It'll be fixed with SugarRecord 2.0
