### ISSUE TITLE
Feature request: querying options add "group by"

### ISSUE THREAD

**Issue by mithvv** [gitdoapp/SugarRecord#123]
If I want to query a Two-Dimension Array, I will use "group by" to query it. Can SugarRecord add it?

```swift
User.by("gender", equalTo: "boy").sorted(by:"name", ascending: true).grouped(by:"age", ascending: false).find()
```

Thanks!

**Comment by pepibumur** [comment]
I can take a look :P

**Comment by eriktelepovsky** [comment]
+1

It will be great it there is an option to count grouped results too.

Thank you

**Comment by pepibumur** [comment]
Swift 2.0 feature
