### ISSUE TITLE
Can't change SugarRecordLogger log level when included with CocoaPods

### ISSUE THREAD

**Issue by mgleason** [gitdoapp/SugarRecord#141]
Guessing that variables in a Dynamic Framework are private by default.  So... 

... in SugarRecordLogger.h need to change:
FROM:             static var currentLevel: SugarRecordLogger = .logLevelInfo
TO:        public static var currentLevel: SugarRecordLogger = .logLevelInfo

**Comment by pbenkoe** [comment]
+1
