### ISSUE TITLE
Multiple stacks of one class interfere with each other 

### ISSUE THREAD

**Issue by ptiz** [gitdoapp/SugarRecord#152]
You can easily create and add two CoreData stacks even with different db file names (test target being started simultaneously with main target, for example), but occasionally got all the records in one place, because there always only one stack of the particular type is being selected internally for all the operations. Why do you prefer to have multiple stacks with singleton-driven environment? What is the profit of this?

**Comment by pepibumur** [comment]
@ptiz totally agree. We'll allow the developer to specify which stack use with the operation. Otherwise it'll use the default one. Adding a note here https://github.com/gitdoapp/SugarRecord/issues/168 for SugarRecord 2.0
