### ISSUE TITLE
Issues on migrating to the latest version of SugarRecord

### ISSUE THREAD

**Issue by AustinChou** [gitdoapp/SugarRecord#154]
Here is some issue I have experienced when migrating from a old version of SR to the latest dev branch version. 

1. Wiki and Example project don't match. Since a new version of SugarRecord based on Swift 1.2, Example project began to use auto saving for DefaultCDStack, and `beginWriting()`, `endWriting()` is no longer needed. In the wiki, it is still required. 

2. If you doesn't modify your stack to enable auto saving, SR behaviors differently than the old version. If you still using `beginWriting()` and `endWriting()` for manually saving, __THIS DOESN'T WORK!__. You can't find recent saved object until SR started its own saving process. 

3. `func by<T: StringLiteralConvertible, R: StringLiteralConvertible>(key: T, equalTo value: R) -> SugarRecordFinder` will not working if R is NSNumber type. This may caused by NSNumber StringLiteralConvertible changes in Swift 1.2

**Comment by funky-monkey** [comment]
+1

**Comment by pepibumur** [comment]
Working on SugarRecord 2.0 @AustinChou and @funky-monkey , I'll keep it in mind
