### ISSUE TITLE
contextCD property of SugarRecordCDContext should be public?

### ISSUE THREAD

**Issue by pbenkoe** [gitdoapp/SugarRecord#155]
hey,

sometimes i need to access the NSManagedObjectContext property of a SugarRecordContext - e.g. for getting a ManagedObject with a given NSManagedObjectID with the existingObjectWithID function. should the contextCD property of the SugarRecordCDContext therefore be public (..using cocoapods) or are you supposed to handle this in another way?

**Comment by pepibumur** [comment]
@pbenkoe we're going to modify this in 2.0 in order to make it "More accessible" for users that want to access the core components behind the framework. Stay tuned
