### ISSUE TITLE
NSSortDescriptors works differently

### ISSUE THREAD

**Issue by tosbaha** [gitdoapp/SugarRecord#159]
I got different results with same NSSortDescriptors. Here is the code
```swift
        let sortDescriptor = NSSortDescriptor(key: "startDate", ascending: false)
        finder.sortDescriptors = [sortDescriptor]
        _fetchedResultsController = finder.fetchedResultsController(nil)
```
tableView result
```
Item A
Item B
Item C
```
If I query all objects I get different order.
```swift
       var users = User.all().sorted(by:"startDate", false).find()
       for user in users {
       	println(user)
       }
```
Result:

```
Item C
Item B
Item A
```
It is very confusing. Is it a bug or for loop gives item in reverse order of fetchedResultsController?

**Comment by pepibumur** [comment]
@tosbaha thanks . Closing this and keeping in mind for 2.0 design.
