### ISSUE TITLE
Swift 2 Support

### ISSUE THREAD

**Issue by xanderdunn** [gitdoapp/SugarRecord#162]
It looks like SugarRecord doesn't compile in a Swift 2 app right now.  Are there plans to swift over to Swift 2?

**Comment by AndreiBoariu** [comment]
Any updates for Swift 2 ?

**Comment by sgxiang** [comment]
Any one to maintain the project?

**Comment by Ged2323** [comment]
I've managed to get the sugar record Swift example running.  What do you mean it's not compiling what issues are you getting?  By the way is there a way to notify the iCloudTableViewController when the iCloud data has loaded? I've tried a few things like NSNotification centre and protocol but can't get it to work based on my limited knowledge with these things.  I've noticed that you have to exit the table and go back in and then the data appears.

**Comment by pepibumur** [comment]
Hey guys!
We've started preparing the Swift2 compatible version with a new API and interesting features. Stay tuned!

**Comment by Tylerc230** [comment]
Has anyone come up with a swift 2.0 compatible fork?

**Comment by pepibumur** [comment]
@Tylerc230 do you use it with CoreData?

**Comment by Tylerc230** [comment]
Yeah I've been using https://github.com/ykobets/SugarRecord
