### ISSUE TITLE
unable to use it via cocoa pods

### ISSUE THREAD

**Issue by aryansbtloe** [gitdoapp/SugarRecord#170]
/usr/bin/pod update

Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to find a specification for `SugarRecord`

**Comment by tosbaha** [comment]
They started from scratch. It is going to take a while. I don't want to disrespect but, it didn't have much support in previous version either. I hope they go strong this time. Since my app was using it, I don't have any choice but to change it. Good luck.

**Comment by pepibumur** [comment]
As @tosbaha we started from Scratch, still building the version2. It'll take a while to have it ready but as soon as we have it we'll reach you.
Sorry @tosbaha about not being able to support the you that much with the previous version. We're trying to do it much better with this version.
