### ISSUE TITLE
Error: filename "Request.swift" used twice

### ISSUE THREAD

**Issue by jakalesmana** [gitdoapp/SugarRecord#172]
When compiling in XCode 7.1 always cause error: filename "Request.swift" used twice.

<unknown>:0: error: filename "Request.swift" used twice: '/.../Pods/SugarRecord/SugarRecord/SugarRecord/Source/Entities/Request.swift' and '/.../Pods/SugarRecord/SugarRecord/SugarRecord/Source/Extension/Request.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by pepibumur** [comment]
Hey @jakalesmana still in development, we'll have the version 2 ready in a couple of weeks

**Comment by jakalesmana** [comment]
Hey @pepibumur do you have a quick workaround? Or should we just wait? Thanks.

**Comment by pepibumur** [comment]
Just wait, the version that is right now available is not ready yet.

**Comment by pepibumur** [comment]
@jakalesmana  you can subscribe to our created mailing list to receive updates.
