### ISSUE TITLE
[!] Unable to find a specification for `SugarRecord`

### ISSUE THREAD

**Issue by Ged2323** [gitdoapp/SugarRecord#173]
Hi I've tried adding to the podfile and running pod install though I'm getting this error.

**Comment by pepibumur** [comment]
Hey @Ged2323 still working on the new version, it's in a broken status. I'll let you know once it's ready. Stay tunned

**Comment by pepibumur** [comment]
You can subscribe to this mailing list to receive updates:
http://eepurl.com/57tqX

**Comment by pepibumur** [comment]
Ready @Ged2323 you can use it now
