### ISSUE TITLE
Build error on CoreDataDefaultStorage

### ISSUE THREAD

**Issue by demonar** [gitdoapp/SugarRecord#174]
After adding the project as an embedded Framework i get this error:

Type 'CoreDataDefaultStorage' does not conform to protocol 'Storage'

as of commit 3cbc530f23863327a7921706fef46b168bb3af6b [3cbc530]

**Comment by pepibumur** [comment]
@demonar version 2.0 is still in progress. I'll have it ready for this week.

**Comment by demonar** [comment]
i thought that, but as the default branch is this one, i wanted to let you know that this was happening.

Sorry for bothering with this, awesome library

**Comment by pepibumur** [comment]
Oh not bothering @demonar . I should be more explicit in the README. @demonar subscribe the mailing list we have, I'll send an email there as soon as we have the new version ready.

**Comment by pepibumur** [comment]
Ready @demonar
