### ISSUE TITLE
Version 2.0 question

### ISSUE THREAD

**Issue by demonar** [gitdoapp/SugarRecord#178]
@pepibumur do you know when you'll be able to release the 2.0 version to carthage users?

**Comment by pepibumur** [comment]
Ey @demonar first week of December will be ready. I'm testing and finishing the core functionality :)

**Comment by felipecarreramo** [comment]
one day in particular of the first week? thanks :+1:

**Comment by pepibumur** [comment]
Ready @felipecarreramo

**Comment by demonar** [comment]
@pepibumur awesome!
