### ISSUE TITLE
cocoapods

### ISSUE THREAD

**Issue by highthem** [gitdoapp/SugarRecord#179]
Hello,

I can't install the pod! can you clarify how to do it with your lib?

**Comment by cboebel** [comment]
I am having this issue as well. 

Simply specifying 

    pod "SugarRecord" 

results in an error 

    [!] Unable to find a specification for `SugarRecord`

Specifying with a version number ( 2.0.0 ) results in the same error.

If you explicitly specify the github repo in the pod file (with and without a branch specified as well), it results in a different error:

    [!] There are only pre-release versions available satisfying the following requirements:

    	'ReactiveCocoa', '~> 4.0'

    	'ReactiveCocoa', '~> 4.0'

    	'ReactiveCocoa', '~> 4.0'
 
    You should explicitly specify the version in order to install a pre-release version

Specifying the repo and the version is not allowed.

Any thoughts?

Thanks!

**Comment by pepibumur** [comment]
Hey @highthem and @cboebel I'm still finishing the version 2.0, I should have it this week with Cocoapods ready. Right now it's broken.

**Comment by cboebel** [comment]
Oh OK, great! Thank you very much. I'm looking forward to trying out your impressive set of functionality and hopefully contributing if I can.

**Comment by highthem** [comment]
@pepibumur thank you :) can't wait to test it

**Comment by pepibumur** [comment]
Ready @cboebel and @highthem
