### ISSUE TITLE
Single quote the string predicates on the finder and consider other types

### ISSUE THREAD

**Issue by pepibumur** [gitdoapp/SugarRecord#88]
### What?
- Commented here: https://github.com/SugarRecord/SugarRecord/pull/87#issuecomment-67567564
Just how we have implemented the finder if you want to filter using an string you have to single-quote it which is something most of users forget about.
- We could split the `by()` method into:
`by(name: String, stringValue: String)`
`by(name: String, intValue: String)` 

###  Steps
- [ ] Add methods to the SugarRecordObjectProtocol
- [ ] Add methods to the Finder
- [ ] **Test** SugarRecord objects methods:
  - [ ] Objective-C
  - [ ] Realm
- [ ] **Teste** SugarRecordFinder methods:
*Note: Basically the tests would consist on  checking if the predicate has the right format*

**Comment by thewhitewood** [comment]
Initially we had migrated from 1.0.3 to 1.0.6 to fix the persistant store on save() call as opposed to move to background...

`func getItemById(value:String) -> ItemVO?{
       let items = ItemVO.by("id", equalTo: value).sorted(by: "id", ascending: true).find()
        let item = items.firstObject() as ItemVO!
        return item
}`

This caused an error which was fixed by accepting the param as an `NSString`

**Comment by pepibumur** [comment]
There's another user reporting problems with Single Quotes: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sugarrecord/P5_qtKeWmic/HM_UIPLmc7oJ
